[[project-setup]]
== プロジェクトのセットアップ

=== bb.edn

バージョン0.3.1以降、babashkaはプロジェクトを管理するためにローカルの`bb.edn`ファイルをサポートしています。

=== :paths と :deps

1つまたは複数のパスと依存関係を宣言することができ、それらは自動的にクラスパスに追加されます。

[source,clojure]
----
{:paths ["script"]
 :deps {medley/medley {:mvn/version "1.3.0"}}}
----

`script/my_project/main.clj` というファイルにmain関数があるとします。

----
(ns my-project.main
  (:require [medley.core :as m]))

(defn -main [& _args]
  (prn (m/index-by :id [{:id 1} {:id 2}])))
----

このように呼び出すことができます。

[source,clojure]
----
$ bb -m my-project.main
{1 {:id 1}, 2 {:id 2}}
----

コマンドラインから関数を呼び出す方法の詳細については <<main-function>> を参照してください。

deps` エントリは https://github.com/borkdude/deps.clj[deps.clj] によって管理され、依存関係を解決してダウンロードするために `java` のインストールが必要です。

=== :min-bb-version

Since version 0.3.6, babashka supports the `:min-bb-version` where the minimal
babashka version can be declared:

[source,clojure]
----
{:paths ["src"]
 :deps {medley/medley {:mvn/version "1.3.0"}}
 :min-bb-version "0.3.7"}
----

When using an older bb version (that supports `:min-bb-version`), babashka will
print a warning:

[source]
----
WARNING: this project requires babashka 0.3.7 or newer, but you have: 0.3.6
----

=== :tasks

Since babashka 0.4.0 the `bb.edn` file supports the `:tasks` entry which
describes tasks that you can run in the current project. The tasks feature is
similar to what people use `Makefile`, `Justfile` or `npm run` for. See <<tasks>> for more details.
