[[usage]]
== Usage

コマンドラインで`bb help`と入力すると、利用可能なすべてのコマンドラインオプションが表示され、babashkaの利用可能な機能を知ることができます。

include::usage/help.adoc[]

=== Running a script

スクリプトをファイルから実行するには、 `-f` または `--file` を使用します。

[source,bash]
----
bb -f download_html.clj
----

ファイルは `-f` を付けずに直接渡すこともできます。

[source,bash]
----
bb download_html.clj
----

shebangで `bb` を使うこともできます。

[source,clojure]
----
include::usage/download_html.clj[]
----

[source,bash]
----
$ ./download_html.clj
Usage: <url> <file>

$ ./download_html.clj https://www.clojure.org /tmp/clojure.org.html
Downloading url: https://www.clojure.org
Writing file: /tmp/clojure.org.html
----

もし、 `/usr/bin/env` ではうまくいかない場合は、以下のような回避策があります。

[source,bash]
----
$ cat script.clj
#!/bin/sh

#_(
   "exec" "bb" "$0" hello "$@"
   )

(prn *command-line-args*)

./script.clj 1 2 3
("hello" "1" "2" "3")
----

=== Current file path

var `*file*` には、現在実行されているファイルのフルパスが入ります。

[source,bash]
----
$ cat example.clj
(prn *file*)

$ bb example.clj
"/Users/borkdude/example.clj"
----

=== Parsing command line arguments

コマンドライン引数は `*command-line-args*` を使って取得することができます。コマンドライン引数を解析したい場合には、組み込みの `clojure.tools.cli` 名前空間を使用することができます。


Babashkaには、 `clojure.tools.cli` が同梱されています。

[source,clojure]
----
(require '[clojure.tools.cli :refer [parse-opts]])

(def cli-options
  ;; An option with a required argument
  [["-p" "--port PORT" "Port number"
    :default 80
    :parse-fn #(Integer/parseInt %)
    :validate [#(< 0 % 0x10000) "Must be a number between 0 and 65536"]]
   ["-h" "--help"]])

(:options (parse-opts *command-line-args* cli-options))
----

[source,bash]
----
$ bb script.clj
{:port 80}
$ bb script.clj -h
{:port 80, :help true}
----

また、babashkaと互換性のある https://github.com/borkdude/babashka/blob/master/doc/projects.md#nubankdocopt[nubank/docopt] ライブラリもあります。

=== Classpath

babashkaのクラスパスに含まれるディレクトリやライブラリを制御するには、 `bb.edn` を使うことをお勧めします。 <<project-setup>> を参照してください。

もし、 `bb.edn` を使わずに、babashkaのクラスパスを低レベルでコントロールしたい場合は、クラスパスをオーバーライドする `—classpath` オプションを使うことができます。 例えば、 `script/my/namespace.clj` というファイルがあるとします。

[source,clojure]
----
(ns my.namespace)
(defn -main [& args]
  (apply println "Hello from my namespace!" args))
----

これで、このmain関数を実行することができます。

[source,clojure]
----
$ bb --classpath script --main my.namespace 1 2 3
Hello from my namespace! 1 2 3
----

このような古典的なClojureプロジェクトのレイアウトを持つ大きなスクリプトの場合は、以下のようになります。

[source,bash]
----
$ tree -L 3
├── deps.edn
├── README
├── src
│   └── project_namespace
│       ├── main.clj
│       └── utilities.clj
└── test
    └── project_namespace
        ├── test_main.clj
        └── test_utilities.clj
----

これを実行すると、クラスパスに `src` と `test` の両方のフォルダを含めるようにbabashkaに指示することができ、socket REPLを開始することができます。

[source,bash]
----
$ bb --classpath src:test socket-repl 1666
----

もし、 `--classpath` という引数がなければ、環境変数 `BABASHKA_CLASSPATH` が使われます。この変数が設定されていない場合、babashkaは `bb.edn` から `:deps` と `:path` を使用します。

 ink:#babashka_classpath[babashka.classpath] 名前空間も参照してください。この名前空間では、クラスパスを動的に追加することができます。

名前空間の link:#babashkadeps[babashka.deps] は、 https://github.com/clojure/tools.deps.alpha[tools.deps] をbabashkaと統合し、 `deps.edn` マップを使ってクラスパスを設定することができます。

[[main-function]]
=== Invoking a main function

メイン関数は上記のように `-m` または `--main` で呼び出すことができます。引数 `foo.bar` が与えられると、名前空間 `foo.bar` が要求され、コマンドライン引数を文字列として、関数 `foo.bar/-main` が呼び出されます。

babashka 0.3.1以降では、 `-m` に完全修飾されたシンボルを渡すことができます。

[source,clojure]
----
$ bb -m clojure.core/prn 1 2 3
"1" "2" "3"
----

このように、提供された引数の数を受け付ける限り、任意の関数をメイン関数として実行することができます。

メイン関数を使って `bb` を起動すると、 `(System/getProperty "babashka.main")` という式がメイン関数の名前を返します。

=== Preloads

環境変数 `BABASHKA_PRELOADS` を使って、以降のbabashkaの使用時に利用可能なコードを定義することができます。

[source,bash]
----
BABASHKA_PRELOADS='(defn foo [x] (+ x 2))'
BABASHKA_PRELOADS=$BABASHKA_PRELOADS' (defn bar [x] (* x 2))'
export BABASHKA_PRELOADS
----

なお、複数の式を連結することも可能です。では、これらの関数をbabashkaで使ってみましょう。

[source,bash]
----
$ bb '(-> (foo *input*) bar)' <<< 1
6
----

また、 `load-file` を使って、ファイル全体をプリロードすることもできます。

[source,bash]
----
export BABASHKA_PRELOADS='(load-file "my_awesome_prelude.clj")'
----

なお、 `*input*` はプリロードでは使用できません。

include::usage/repl.adoc[]

include::usage/io-flags.adoc[]

=== Uberscript

オプション `--uberscript` は `BABASHKA_PRELOADS` にある式、コマンドラインの式またはファイル、メインエントリーポイント、クラスパスから必要な全ての名前空間を一つのファイルに集めます。これは、デバッグやデプロイメントに便利です。

ここでは、https://github.com/clj-commons/fs[clj-commons/fs] ライブラリの関数を使用した例を示します。

まず、クラスパスを設定します。

[source,clojure]
----
$ export BABASHKA_CLASSPATH=$(clojure -Spath -Sdeps '{:deps {clj-commons/fs {:mvn/version "1.6.307"}}}')
----

小さなスクリプト、例えば `glob.clj` を書いてみてください。

[source,clojure]
----
(ns glob (:require [me.raynes.fs :as fs]))

(run! (comp println str)
      (fs/glob (first *command-line-args*)))
----

試しに、glob関数を使って検索するファイルを作ってみます。

[source,bash]
----
$ touch README.md
----

これで、ライブラリを利用したスクリプトを実行できるようになりました。

[source,bash]
----
$ time bb glob.clj '*.md'
/private/tmp/glob/README.md
bb glob.clj '*.md'   0.03s  user 0.01s system 88% cpu 0.047 total
----

必要なコードをすべて含むuberscriptを作成すること。

[source,bash]
----
$ bb uberscript glob-uberscript.clj -f glob.clj
----

クラスパスがもう必要ないことを証明するために。

[source,bash]
----
$ unset BABASHKA_CLASSPATH
$ time bb glob-uberscript.clj '*.md'
/private/tmp/glob/README.md
bb glob-uberscript.clj '*.md'   0.03s  user 0.02s system 93% cpu 0.049 total
----

注意事項

* 動的な要求(Dynamic requires)。uberscripts のビルドは、トップレベルの `ns` と `require` フォームを実行することで動作します。残りのコードは評価されません。動的な要求に依存するコードは、uberscript では動作しないかもしれません。* _Resources_. io/resource` の使用はクラスパスを想定しているので、これをuberscriptで使用する場合、やはりクラスパスを設定し、リソースを持参する必要があります。

上記のいずれかがプロジェクトにとって問題である場合、 link:#uberjar[uberjar] を使用することが良い代替方法となります。

==== Carve

Uberscriptsは、 https://github.com/borkdude/carve[carve] で使用しないバーをカットすることで最適化することができます。

[source,bash]
----
$ wc -l glob-uberscript.clj
     583 glob-uberscript.clj
$ carve --opts '{:paths ["glob-uberscript.clj"] :aggressive true :silent true}'
$ wc -l glob-uberscript.clj
     105 glob-uberscript.clj
----

uberscriptが72%短くなったことに注目してほしい。これは実行時間に対して有益な効果である。

[source,bash]
----
$ time bb glob-uberscript.clj '*.md'
/private/tmp/glob/README.md
bb glob-uberscript.clj '*.md'   0.02s  user 0.01s system 84% cpu 0.034 total
----

=== Uberjar

Babashkaは指定されたクラスパスと、オプションでメインメソッドからユーバージャーを作成することができます。

[source,clojure]
----
$ cat src/foo.clj
(ns foo (:gen-class)) (defn -main [& args] (prn :hello))
$ bb -cp $(clojure -Spath) uberjar foo.jar -m foo
$ bb foo.jar
:hello
----

`clojure` や `deps.clj` ツールを使ってクラスパスを作成すると、Clojure 自身やspec、コアスペックがクラスパスに含まれるため、uberjar が必要以上に肥大化することになります。

[source,bash]
----
$ ls -lh foo.jar
-rw-r--r--  1 borkdude  staff   4.5M Aug 19 17:04 foo.jar
----

これらの依存関係を除外するには、`deps.edn` で以下の `:classpath-overrides` を使用します。

[source,clojure]
----
{:aliases {:remove-clojure {:classpath-overrides {org.clojure/clojure nil
                                                  org.clojure/spec.alpha nil
                                                  org.clojure/core.specs.alpha nil}}}}
----

[source,clojure]
----
$ rm foo.jar
$ bb -cp $(clojure -A:remove-clojure -Spath) uberjar foo.jar -m foo
$ bb foo.jar
:hello
$ ls -lh foo.jar
-rw-r--r--  1 borkdude  staff   871B Aug 19 17:07 foo.jar
----

uberjarをJVMに対応させたい場合は、mainの名前空間をコンパイルする必要があります。Babashkaはコンパイルを行わないので、その部分はJVM上のClojureを使用します。

[source,clojure]
----
$ rm foo.jar
$ mkdir classes
$ clojure -e "(require 'foo) (compile 'foo)"
foo
$ bb -cp $(clojure -Spath):classes uberjar foo.jar -m foo
$ bb foo.jar
:hello
$ java -jar foo.jar
:hello
----

=== システムプロパティ

ババシュカでは、以下のシステムプロパティを設定します。

* `babashka.version`: バージョンの文字列 (例: `"1.2.0"`)
* `babashka.main`: 引数 `--main` です。
* `babashka.file`: `--file` 引数 (`.getAbsolutePath` を使用して正規化)

=== データリーダー

データリーダを有効にするには、`*data-readers*` にシンボルと関数またはバーのハッシュマップを設定します。

[source,clojure]
----
$ bb -e "(set! *data-readers* {'t/tag inc}) #t/tag 1"
2
----

良好なスタートアップ時間を維持するために、babashkaはクラスパスで `data_readers.clj` ファイルをスキャンしません。

=== Reader conditionals

Babashka supports reader conditionals by taking either the `:bb` or `:clj` branch, whichever comes first. NOTE: the `:clj` branch behavior was added in version 0.0.71, before that version the `:clj` branch was ignored.

[source,clojure]
----
$ bb -e "#?(:bb :hello :clj :bye)"
:hello

$ bb -e "#?(:clj :bye :bb :hello)"
:bye

$ bb -e "[1 2 #?@(:bb [] :clj [1])]"
[1 2]
----

=== Invoking clojure

Babashka bundles https://github.com/borkdude/deps.clj[deps.clj] for invoking a `clojure` JVM process:

[source,clojure]
----
$ bb clojure -M -e "*clojure-version*"
{:major 1, :minor 10, :incremental 1, :qualifier nil}
----

See the link:#_clojure[clojure] function in the link:#babashkadeps[babashka.deps] namespace for programmatically invoking clojure.
